CREATE DATABASE alexandra 
GO
USE alexandra 
GO

-- Creacion de tablas
CREATE TABLE Maestro (
    Id INT NOT NULL,
    Nombre VARCHAR(100) NOT NULL
)

CREATE TABLE Clase (
    Id INT NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Aula INT NOT NULL,
    Horario VARCHAR(50) NOT NULL,
    IdMaestro INT NOT NULL
)

--CREACION DE PRIMARY KEY
ALTER TABLE MAestro ADD CONSTRAINT PK_Maestro PRIMARY KEY (ID)

ALTER TABLE Clase ADD CONSTRAINT PK_CLASE PRIMARY KEY (ID)

--CREACION DE FOREIGN KEY
ALTER TABLE CLASE ADD CONSTRAINT FK_CLASE_MAESTRO
FOREIGN KEY (IDMAESTRO) REFERENCES MAESTRO (ID)

